#!/bin/bash
sudo apt update
wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.6-bin.zip
sudo apt insatll -y zip
unzip apache-maven-3.9.6-bin.zip
sudo ln -s /home/ubuntu/apache-maven-3.9.6/bin/nvn /usr/local/sbin/nvn
sudo chmod 777 /usr/local/sbin/nvn
